# Generated by Django 5.2.3 on 2025-06-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'absencestype',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('ach_code', models.CharField(blank=True, max_length=255, null=True)),
                ('check_digit', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_current', models.CharField(max_length=255)),
                ('account_savings', models.CharField(max_length=255)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('city_code', models.CharField(max_length=10)),
                ('department_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=10485760, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract_templates',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dian_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract_types',
            },
        ),
        migrations.CreateModel(
            name='ContributorType',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('plan_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contributor_types',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
                ('dian_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_types',
            },
        ),
        migrations.CreateModel(
            name='PayrollType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dian_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll_types',
            },
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'salary_types',
            },
        ),
        migrations.CreateModel(
            name='SocialSecurityEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('tax_id', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=20)),
                ('sgp_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'social_security_entities',
            },
        ),
        migrations.CreateModel(
            name='StructureLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'structure_levels',
            },
        ),
        migrations.CreateModel(
            name='SubtypeContributor',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subtype_contributors',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'years',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('verification_digit', models.CharField(max_length=10)),
                ('doc_type', models.CharField(max_length=2)),
                ('legal_representative', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('payroll_contact', models.CharField(max_length=50)),
                ('payroll_email', models.CharField(max_length=50)),
                ('hr_contact', models.CharField(max_length=50)),
                ('hr_email', models.CharField(max_length=50)),
                ('accounting_contact', models.CharField(max_length=50)),
                ('accounting_email', models.CharField(max_length=50)),
                ('cert_position', models.CharField(max_length=50)),
                ('cert_signature', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=40, null=True)),
                ('extra_method', models.CharField(blank=True, max_length=255, null=True)),
                ('parafiscals', models.CharField(blank=True, max_length=2, null=True)),
                ('ccf_value', models.CharField(blank=True, max_length=2, null=True)),
                ('sena_icbf_value', models.CharField(blank=True, max_length=2, null=True)),
                ('pension_limit', models.CharField(blank=True, max_length=2, null=True)),
                ('pension_rate', models.CharField(blank=True, max_length=2, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=10, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=40, null=True)),
                ('contributor_class', models.CharField(blank=True, max_length=1, null=True)),
                ('contributor_type', models.SmallIntegerField(blank=True, null=True)),
                ('adjust_news', models.CharField(blank=True, max_length=2, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.bank')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.country')),
                ('arl_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arl_contracts', to='common.socialsecurityentity')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, to='common.company'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_type', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=25, null=True)),
                ('withholding_method', models.CharField(blank=True, max_length=25, null=True)),
                ('withholding_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('housing_deduction', models.IntegerField(blank=True, null=True)),
                ('health_withholding', models.IntegerField(blank=True, null=True)),
                ('retired_status', models.CharField(blank=True, max_length=25, null=True)),
                ('liquidation_status', models.CharField(blank=True, max_length=25, null=True)),
                ('social_security_status', models.CharField(blank=True, max_length=25, null=True)),
                ('retirement_reason', models.CharField(blank=True, max_length=25, null=True)),
                ('variable_salary', models.SmallIntegerField(blank=True, default=2, null=True)),
                ('transport_assistance', models.BooleanField(default=False)),
                ('dependents', models.SmallIntegerField(blank=True, null=True)),
                ('medical_deduction', models.IntegerField(blank=True, null=True)),
                ('work_shift', models.CharField(blank=True, max_length=25, null=True)),
                ('pension_risk', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.company')),
                ('hiring_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.city')),
                ('contract_template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.contracttemplate')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.contracttype')),
                ('contributor_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.contributortype')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('hours_to_deduct', models.IntegerField(blank=True, null=True)),
                ('novelty_date', models.DateField(blank=True, null=True)),
                ('authorized_by', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_hours', models.IntegerField(blank=True, null=True)),
                ('absence_status', models.SmallIntegerField(blank=True, null=True)),
                ('payroll_id', models.IntegerField(blank=True, null=True)),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.absencetype')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.contract')),
            ],
            options={
                'db_table': 'absences',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('accounting_group', models.CharField(blank=True, max_length=4, null=True)),
                ('cost_code', models.CharField(blank=True, max_length=2, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.company')),
            ],
            options={
                'db_table': 'cost_center',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.costcenter'),
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identification_number', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=180, null=True)),
                ('education_level', models.CharField(blank=True, max_length=25, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('resume_format', models.CharField(blank=True, max_length=25, null=True)),
                ('pants_size', models.CharField(blank=True, max_length=10, null=True)),
                ('shirt_size', models.CharField(blank=True, max_length=10, null=True)),
                ('shoe_size', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_status', models.SmallIntegerField(blank=True, null=True)),
                ('socioeconomic_stratum', models.CharField(blank=True, max_length=5, null=True)),
                ('military_book_number', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.CharField(blank=True, max_length=25, null=True)),
                ('birth_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='birth_city', to='common.city')),
                ('birth_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='birth_country', to='common.country')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.company')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.documenttype')),
                ('issue_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issue_city', to='common.city')),
                ('residence_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='residence_city', to='common.city')),
                ('residence_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='residence_country', to='common.country')),
            ],
            options={
                'db_table': 'employee_contracts',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.employeecontract'),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('compensation_box', models.CharField(blank=True, max_length=60, null=True)),
                ('compensation_code', models.CharField(blank=True, max_length=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.company')),
            ],
            options={
                'db_table': 'offices',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.office'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payroll_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.payrolltype'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.company')),
                ('structure_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.structurelevel')),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.position'),
        ),
        migrations.AddField(
            model_name='contract',
            name='salary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.salarytype'),
        ),
        migrations.AddField(
            model_name='contract',
            name='compensation_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts_ccf', to='common.socialsecurityentity'),
        ),
        migrations.AddField(
            model_name='contract',
            name='eps_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts_eps', to='common.socialsecurityentity'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pension_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts_afp', to='common.socialsecurityentity'),
        ),
        migrations.AddField(
            model_name='contract',
            name='severance_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts_severance', to='common.socialsecurityentity'),
        ),
        migrations.CreateModel(
            name='Subcost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('subcost_code', models.CharField(blank=True, max_length=2, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.company')),
                ('cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.costcenter')),
            ],
            options={
                'db_table': 'subcosts',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='sub_cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.subcost'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sub_contributor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.subtypecontributor'),
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('arl_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('previous_center', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.company')),
            ],
            options={
                'db_table': 'work_centers',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.workcenter'),
        ),
    ]
